[package]
name = "embedded-jsonrpc"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3", optional = true }
embedded-io-async = { version = "0.6.1" }
heapless = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"

[dev-dependencies]
tokio = { version = "1.41.1", features = ["full"] }

[features]
default = []
defmt = ["dep:defmt"]